### ISSUE TITLE
Strontium determination

### ISSUE THREAD

**Issue by kittyp** [mpokorny/h2odb#11]
We need to change the criteria that the chemistry software uses to determine which strontium value to input to the database.

There are two strontium (Sr) values provided for each chemistry sample. They are differentiated by a test name in the Test field of the spreadsheet. Currently, the chemistry software looks for a complete test name match to determine which Sr value to input. However, the test name has been changing somewhat, so I would like to have the chemistry software only look for a certain word in the Test field name.

For the Param Sr, I would like the chemistry software to look in the Test field for the terms Cation and Trace metals and make a determination based on only those words. In other words, I would like to have wild card characters after the word Cations and Trace metals, and I would also like them to be case insensitive.

'Kay?

**Comment by mpokorny** [comment]
Done in v0.9.2.
