### ISSUE TITLE
Hiccups in latest (.7) version of h2odb

### ISSUE THREAD

**Issue by kittyp** [mpokorny/h2odb#4]
Input some data using latest version. Just a couple of issues.

1) Iron (Fe) had a non-detect level that was supposed to be < 0.1 mg/L (5 dilution factor x 0.02 reporting limit = 0.1 mg/L reporting limit), but it reported < 0.09999999 instead.

2) Thallium (Tl) had a correctly recorded non-detect level in the database (< 0.0025 mg/L), but sent the result as a failure of water quality (water quality standard for Thallium is 0.002 mg/L). A tricky place, because we don't know how much <0.0025 mg/L it is; 0.0023? 0.0019? I like that it reported it even if it's border line, so let's not change that, but in the report of failed water quality standards it said Tl (0.0025000002 mg/L). Seems a little confused.

That's it. Otherwise it worked great. Have another need though. Will do a new issue report for enhancement of system.

Kitty

**Comment by mpokorny** [comment]
It's just an output formatting issue. I won't change anything to fix it unless you decide on some consistent format that you'd prefer.
