### ISSUE TITLE
Application not opening

### ISSUE THREAD

**Issue by kittyp** [mpokorny/h2odb#8]
The window to select the spreadsheet and then select the database for entering chemistry did not open today. I checked for the latest version on GitHub, updated the config file in NotePad, then launched the H2Odb.bat file, but the selection dialog box did not open. - Kitty

**Comment by mpokorny** [comment]
Try version 0.6.4; I think that the error may have been in the launcher script that's packaged with the release (although I'm not sure why that would be used in any way).

**Comment by mpokorny** [comment]
There was a dependency on scala version 2.10 in application's scala code (App.scala). It's been changed to 2.11.4.

**Comment by mpokorny** [comment]
Fixed
